from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_loginwindow(object):
    def setupUi(self, loginwindow):
        loginwindow.setObjectName("loginwindow")
        loginwindow.resize(400, 400)
        loginwindow.setMinimumSize(QtCore.QSize(400, 400))
        loginwindow.setMaximumSize(QtCore.QSize(400, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("12345.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        loginwindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(loginwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 400, 400))
        self.groupBox.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 0, 102), stop:0.326316 rgba(255, 0, 0, 130), stop:0.339799 rgba(255, 255, 255, 255), stop:0.636842 rgba(255, 255, 255, 135), stop:0.662469 rgba(0, 0, 255, 255), stop:1 rgba(0, 0, 255, 95));")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 180, 141, 40))
        self.label_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgba(255, 255, 255, 10);")
        self.label_2.setObjectName("label_2")
        self.username_edit = QtWidgets.QLineEdit(self.groupBox)
        self.username_edit.setGeometry(QtCore.QRect(180, 180, 191, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.username_edit.setFont(font)
        self.username_edit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.username_edit.setText("")
        self.username_edit.setObjectName("username_edit")
        self.login_button = QtWidgets.QPushButton(self.groupBox)
        self.login_button.setGeometry(QtCore.QRect(100, 290, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.login_button.setFont(font)
        self.login_button.setStyleSheet("border: 2px solid black; background-color: rgba(255, 255, 255, 150);")
        self.login_button.setObjectName("login_button")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(110, 60, 181, 40))
        self.label_3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgba(255, 255, 255, 10);")
        self.label_3.setObjectName("label_3")
        loginwindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(loginwindow)
        QtCore.QMetaObject.connectSlotsByName(loginwindow)

    def retranslateUi(self, loginwindow):
        _translate = QtCore.QCoreApplication.translate
        loginwindow.setWindowTitle(_translate("loginwindow", "PyboysFlashcards"))
        self.label_2.setText(_translate("loginwindow", "User name:"))
        self.login_button.setText(_translate("loginwindow", "Login"))
        self.label_3.setText(_translate("loginwindow", "PyboysFlashcards"))

        self.login_button.clicked.connect(self.Login)
    def Login(self):
        self.ui = Ui_menu_window()
        self.ui.setupUi(loginwindow)


class Ui_menu_window(object):


    def setupUi(self, menu_window):
        menu_window.setObjectName("menu_window")
        menu_window.resize(570, 550)
        menu_window.setMinimumSize(QtCore.QSize(570, 550))
        menu_window.setMaximumSize(QtCore.QSize(570, 550))
        menu_window.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(menu_window)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 570, 550))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 0, 102), stop:0.326316 rgba(255, 0, 0, 130), stop:0.339799 rgba(255, 255, 255, 255), stop:0.636842 rgba(255, 255, 255, 135), stop:0.662469 rgba(0, 0, 255, 255), stop:1 rgba(0, 0, 255, 95));")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.which_user = QtWidgets.QLabel(self.groupBox)
        self.which_user.setGeometry(QtCore.QRect(290, 30, 140, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.which_user.setFont(font)
        self.which_user.setStyleSheet("background-color: rgba(255, 255, 255, 10);")
        self.which_user.setText("")
        self.which_user.setObjectName("which_user")
        self.progress_label = QtWidgets.QLabel(self.groupBox)
        self.progress_label.setGeometry(QtCore.QRect(40, 100, 140, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.progress_label.setFont(font)
        self.progress_label.setStyleSheet("background-color: rgba(255, 255, 255, 10);")
        self.progress_label.setObjectName("progress_label")
        self.progress = QtWidgets.QProgressBar(self.groupBox)
        self.progress.setGeometry(QtCore.QRect(190, 100, 341, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progress.setFont(font)
        self.progress.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.progress.setProperty("value", 24)
        self.progress.setObjectName("progress")
        self.level_label = QtWidgets.QLabel(self.groupBox)
        self.level_label.setGeometry(QtCore.QRect(40, 190, 101, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.level_label.setFont(font)
        self.level_label.setStyleSheet("background-color: rgb(255, 255, 255,10);")
        self.level_label.setObjectName("level_label")
        self.progress_label_5 = QtWidgets.QLabel(self.groupBox)
        self.progress_label_5.setGeometry(QtCore.QRect(40, 280, 131, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.progress_label_5.setFont(font)
        self.progress_label_5.setStyleSheet("background-color: rgb(255, 255, 255,10);")
        self.progress_label_5.setObjectName("progress_label_5")
        self.total_time_show = QtWidgets.QLabel(self.groupBox)
        self.total_time_show.setGeometry(QtCore.QRect(190, 280, 141, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.total_time_show.setFont(font)
        self.total_time_show.setStyleSheet("background-color: rgb(255, 255, 255,10);")
        self.total_time_show.setText("")
        self.total_time_show.setObjectName("total_time_show")
        self.play = QtWidgets.QPushButton(self.groupBox)
        self.play.setGeometry(QtCore.QRect(75, 430, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.play.setFont(font)
        self.play.setAutoFillBackground(False)
        self.play.setStyleSheet("background-color: rgb(255, 255, 255,150);")
        self.play.setObjectName("play")
        self.quit_2 = QtWidgets.QPushButton(self.groupBox)
        self.quit_2.setGeometry(QtCore.QRect(235, 430, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.quit_2.setFont(font)
        self.quit_2.setStyleSheet("background-color: rgb(255, 255, 255,150);")
        self.quit_2.setObjectName("quit_2")
        self.which_user_label = QtWidgets.QLabel(self.groupBox)
        self.which_user_label.setGeometry(QtCore.QRect(170, 30, 121, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.which_user_label.setFont(font)
        self.which_user_label.setStyleSheet("background-color: rgba(255, 255, 255, 10);")
        self.which_user_label.setObjectName("which_user_label")
        self.quit = QtWidgets.QPushButton(self.groupBox)
        self.quit.setGeometry(QtCore.QRect(395, 430, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.quit.setFont(font)
        self.quit.setStyleSheet("background-color: rgb(255, 255, 255,150);")
        self.quit.setObjectName("quit")
        self.level = QtWidgets.QLabel(self.groupBox)
        self.level.setGeometry(QtCore.QRect(190, 190, 141, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.level.setFont(font)
        self.level.setStyleSheet("background-color: rgb(255, 255, 255,10);")
        self.level.setText("")
        self.level.setObjectName("level")
        self.words_counter = QtWidgets.QLabel(self.groupBox)
        self.words_counter.setGeometry(QtCore.QRect(360, 190, 61, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.words_counter.setFont(font)
        self.words_counter.setStyleSheet("background-color: rgb(255, 255, 255,10);")
        self.words_counter.setText("")
        self.words_counter.setObjectName("words_counter")
        self.words_counter_2 = QtWidgets.QLabel(self.groupBox)
        self.words_counter_2.setGeometry(QtCore.QRect(420, 190, 101, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.words_counter_2.setFont(font)
        self.words_counter_2.setStyleSheet("background-color: rgb(255, 255, 255,10);")
        self.words_counter_2.setText("")
        self.words_counter_2.setObjectName("words_counter_2")
        menu_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(menu_window)
        QtCore.QMetaObject.connectSlotsByName(menu_window)

    def retranslateUi(self, menu_window):
        _translate = QtCore.QCoreApplication.translate
        menu_window.setWindowTitle(_translate("menu_window", "PyBoysFlashcards"))
        self.progress_label.setText(_translate("menu_window", "Progress:"))
        self.level_label.setText(_translate("menu_window", "Level:"))
        self.progress_label_5.setText(_translate("menu_window", "Total Time:"))
        self.play.setText(_translate("menu_window", "Play"))
        self.quit_2.setText(_translate("menu_window", "Log Out"))
        self.which_user_label.setText(_translate("menu_window", "Welkom  "))
        self.quit.setText(_translate("menu_window", "Quit"))


        self.play.clicked.connect(self.Play)
        self.quit_2.clicked.connect(self.LogOut)
        self.quit.clicked.connect(self.Quit)
        

    def Play(self):
        self.ui = Ui_MainWindow()
        self.ui.setupUi(loginwindow)
    
    def LogOut(self):
        self.ui = Ui_MainWindow()
        self.ui.setupUi(loginwindow)
    
    def Quit(self):
        quit()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 0, 102), stop:0.326316 rgba(255, 0, 0, 130), stop:0.339799 rgba(255, 255, 255, 255), stop:0.636842 rgba(255, 255, 255, 135), stop:0.662469 rgba(0, 0, 255, 255), stop:1 rgba(0, 0, 255, 95));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.true_button = QtWidgets.QPushButton(self.frame)
        self.true_button.setGeometry(QtCore.QRect(500, 450, 120, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.true_button.setFont(font)
        self.true_button.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(79, 158, 0);")
        self.true_button.setObjectName("true_button")
        self.false_button = QtWidgets.QPushButton(self.frame)
        self.false_button.setGeometry(QtCore.QRect(180, 450, 120, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.false_button.setFont(font)
        self.false_button.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);")
        self.false_button.setObjectName("false_button")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(530, 30, 111, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255,10);")
        self.label_3.setObjectName("label_3")
        self.allwords = QtWidgets.QLCDNumber(self.frame)
        self.allwords.setGeometry(QtCore.QRect(720, 20, 51, 51))
        self.allwords.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.allwords.setDigitCount(2)
        self.allwords.setProperty("value", 20.0)
        self.allwords.setProperty("intValue", 20)
        self.allwords.setObjectName("allwords")
        self.time_lcd_word = QtWidgets.QLCDNumber(self.frame)
        self.time_lcd_word.setGeometry(QtCore.QRect(350, 90, 111, 101))
        self.time_lcd_word.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.time_lcd_word.setDigitCount(1)
        self.time_lcd_word.setObjectName("time_lcd_word")
        self.word = QtWidgets.QLabel(self.frame)
        self.word.setGeometry(QtCore.QRect(40, 210, 720, 170))
        font = QtGui.QFont()
        font.setPointSize(52)
        font.setBold(True)
        font.setWeight(75)
        self.word.setFont(font)
        self.word.setAutoFillBackground(False)
        self.word.setStyleSheet("background-color: rgb(255, 255, 255,10);\n"
"color: rgb(0, 0, 255);")
        self.word.setText("")
        self.word.setAlignment(QtCore.Qt.AlignCenter)
        self.word.setObjectName("word")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(620, 530, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255,10);")
        self.pushButton.setObjectName("pushButton")
        self.known_word_lcd_2 = QtWidgets.QLCDNumber(self.frame)
        self.known_word_lcd_2.setGeometry(QtCore.QRect(630, 20, 60, 51))
        self.known_word_lcd_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.known_word_lcd_2.setDigitCount(2)
        self.known_word_lcd_2.setProperty("intValue", 0)
        self.known_word_lcd_2.setObjectName("known_word_lcd_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(690, 20, 31, 51))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255,10);\n"
"font: 48pt \"MS Shell Dlg 2\";")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyBoysFlashcards"))
        self.true_button.setText(_translate("MainWindow", "True"))
        self.false_button.setText(_translate("MainWindow", "False"))
        self.label_3.setText(_translate("MainWindow", "Progress:"))
        self.pushButton.setText(_translate("MainWindow", "End Game"))
        self.label.setText(_translate("MainWindow", "/"))

        self.pushButton.clicked.connect(self.EndGame)
    def EndGame(self):
        self.ui = Ui_MainWindow()
        self.ui.setupUi(loginwindow)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loginwindow = QtWidgets.QMainWindow()
    ui = Ui_loginwindow()
    ui.setupUi(loginwindow)
    loginwindow.show()
    sys.exit(app.exec_())
