# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gamescreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 0, 102), stop:0.326316 rgba(255, 0, 0, 130), stop:0.339799 rgba(255, 255, 255, 255), stop:0.636842 rgba(255, 255, 255, 135), stop:0.662469 rgba(0, 0, 255, 255), stop:1 rgba(0, 0, 255, 95));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.true_button = QtWidgets.QPushButton(self.frame)
        self.true_button.setGeometry(QtCore.QRect(500, 450, 120, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.true_button.setFont(font)
        self.true_button.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(79, 158, 0);")
        self.true_button.setObjectName("true_button")
        self.false_button = QtWidgets.QPushButton(self.frame)
        self.false_button.setGeometry(QtCore.QRect(180, 450, 120, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.false_button.setFont(font)
        self.false_button.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);")
        self.false_button.setObjectName("false_button")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(530, 30, 111, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255,10);")
        self.label_3.setObjectName("label_3")
        self.allwords = QtWidgets.QLCDNumber(self.frame)
        self.allwords.setGeometry(QtCore.QRect(720, 20, 51, 51))
        self.allwords.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.allwords.setDigitCount(2)
        self.allwords.setProperty("value", 20.0)
        self.allwords.setProperty("intValue", 20)
        self.allwords.setObjectName("allwords")
        self.time_lcd_word = QtWidgets.QLCDNumber(self.frame)
        self.time_lcd_word.setGeometry(QtCore.QRect(350, 90, 111, 101))
        self.time_lcd_word.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.time_lcd_word.setDigitCount(1)
        self.time_lcd_word.setObjectName("time_lcd_word")
        self.word = QtWidgets.QLabel(self.frame)
        self.word.setGeometry(QtCore.QRect(40, 210, 720, 170))
        font = QtGui.QFont()
        font.setPointSize(52)
        font.setBold(True)
        font.setWeight(75)
        self.word.setFont(font)
        self.word.setAutoFillBackground(False)
        self.word.setStyleSheet("background-color: rgb(255, 255, 255,10);\n"
"color: rgb(0, 0, 255);")
        self.word.setText("")
        self.word.setAlignment(QtCore.Qt.AlignCenter)
        self.word.setObjectName("word")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(620, 530, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255,10);")
        self.pushButton.setObjectName("pushButton")
        self.known_word_lcd_2 = QtWidgets.QLCDNumber(self.frame)
        self.known_word_lcd_2.setGeometry(QtCore.QRect(630, 20, 60, 51))
        self.known_word_lcd_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.known_word_lcd_2.setDigitCount(2)
        self.known_word_lcd_2.setProperty("intValue", 0)
        self.known_word_lcd_2.setObjectName("known_word_lcd_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(690, 20, 31, 51))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255,10);\n"
"font: 48pt \"MS Shell Dlg 2\";")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyBoysFlashcards"))
        self.true_button.setText(_translate("MainWindow", "True"))
        self.false_button.setText(_translate("MainWindow", "False"))
        self.label_3.setText(_translate("MainWindow", "Progress:"))
        self.pushButton.setText(_translate("MainWindow", "End Game"))
        self.label.setText(_translate("MainWindow", "/"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())