from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_menu_window(object):
    def setupUi(self, menu_window):
        menu_window.setObjectName("menu_window")
        menu_window.resize(570, 550)
        menu_window.setMinimumSize(QtCore.QSize(570, 550))
        menu_window.setMaximumSize(QtCore.QSize(570, 550))
        menu_window.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(menu_window)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 570, 550))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 0, 102), stop:0.326316 rgba(255, 0, 0, 130), stop:0.339799 rgba(255, 255, 255, 255), stop:0.636842 rgba(255, 255, 255, 135), stop:0.662469 rgba(0, 0, 255, 255), stop:1 rgba(0, 0, 255, 95));")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.which_user = QtWidgets.QLabel(self.groupBox)
        self.which_user.setGeometry(QtCore.QRect(290, 30, 140, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.which_user.setFont(font)
        self.which_user.setStyleSheet("background-color: rgba(255, 255, 255, 10);")
        self.which_user.setText("")
        self.which_user.setObjectName("which_user")
        self.progress_label = QtWidgets.QLabel(self.groupBox)
        self.progress_label.setGeometry(QtCore.QRect(40, 100, 140, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.progress_label.setFont(font)
        self.progress_label.setStyleSheet("background-color: rgba(255, 255, 255, 10);")
        self.progress_label.setObjectName("progress_label")
        self.progress = QtWidgets.QProgressBar(self.groupBox)
        self.progress.setGeometry(QtCore.QRect(190, 100, 341, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progress.setFont(font)
        self.progress.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.progress.setProperty("value", 24)
        self.progress.setObjectName("progress")
        self.level_label = QtWidgets.QLabel(self.groupBox)
        self.level_label.setGeometry(QtCore.QRect(40, 190, 101, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.level_label.setFont(font)
        self.level_label.setStyleSheet("background-color: rgb(255, 255, 255,10);")
        self.level_label.setObjectName("level_label")
        self.progress_label_5 = QtWidgets.QLabel(self.groupBox)
        self.progress_label_5.setGeometry(QtCore.QRect(40, 280, 131, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.progress_label_5.setFont(font)
        self.progress_label_5.setStyleSheet("background-color: rgb(255, 255, 255,10);")
        self.progress_label_5.setObjectName("progress_label_5")
        self.total_time_show = QtWidgets.QLabel(self.groupBox)
        self.total_time_show.setGeometry(QtCore.QRect(190, 280, 141, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.total_time_show.setFont(font)
        self.total_time_show.setStyleSheet("background-color: rgb(255, 255, 255,10);")
        self.total_time_show.setText("")
        self.total_time_show.setObjectName("total_time_show")
        self.play = QtWidgets.QPushButton(self.groupBox)
        self.play.setGeometry(QtCore.QRect(75, 430, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.play.setFont(font)
        self.play.setAutoFillBackground(False)
        self.play.setStyleSheet("background-color: rgb(255, 255, 255,150);")
        self.play.setObjectName("play")
        self.quit_2 = QtWidgets.QPushButton(self.groupBox)
        self.quit_2.setGeometry(QtCore.QRect(235, 430, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.quit_2.setFont(font)
        self.quit_2.setStyleSheet("background-color: rgb(255, 255, 255,150);")
        self.quit_2.setObjectName("quit_2")
        self.which_user_label = QtWidgets.QLabel(self.groupBox)
        self.which_user_label.setGeometry(QtCore.QRect(170, 30, 121, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.which_user_label.setFont(font)
        self.which_user_label.setStyleSheet("background-color: rgba(255, 255, 255, 10);")
        self.which_user_label.setObjectName("which_user_label")
        self.quit = QtWidgets.QPushButton(self.groupBox)
        self.quit.setGeometry(QtCore.QRect(395, 430, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.quit.setFont(font)
        self.quit.setStyleSheet("background-color: rgb(255, 255, 255,150);")
        self.quit.setObjectName("quit")
        self.level = QtWidgets.QLabel(self.groupBox)
        self.level.setGeometry(QtCore.QRect(190, 190, 141, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.level.setFont(font)
        self.level.setStyleSheet("background-color: rgb(255, 255, 255,10);")
        self.level.setText("")
        self.level.setObjectName("level")
        self.words_counter = QtWidgets.QLabel(self.groupBox)
        self.words_counter.setGeometry(QtCore.QRect(360, 190, 61, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.words_counter.setFont(font)
        self.words_counter.setStyleSheet("background-color: rgb(255, 255, 255,10);")
        self.words_counter.setText("")
        self.words_counter.setObjectName("words_counter")
        self.words_counter_2 = QtWidgets.QLabel(self.groupBox)
        self.words_counter_2.setGeometry(QtCore.QRect(420, 190, 101, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.words_counter_2.setFont(font)
        self.words_counter_2.setStyleSheet("background-color: rgb(255, 255, 255,10);")
        self.words_counter_2.setText("")
        self.words_counter_2.setObjectName("words_counter_2")
        menu_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(menu_window)
        QtCore.QMetaObject.connectSlotsByName(menu_window)

    def retranslateUi(self, menu_window):
        _translate = QtCore.QCoreApplication.translate
        menu_window.setWindowTitle(_translate("menu_window", "PyBoysFlashcards"))
        self.progress_label.setText(_translate("menu_window", "Progress:"))
        self.level_label.setText(_translate("menu_window", "Level:"))
        self.progress_label_5.setText(_translate("menu_window", "Total Time:"))
        self.play.setText(_translate("menu_window", "Play"))
        self.quit_2.setText(_translate("menu_window", "Log Out"))
        self.which_user_label.setText(_translate("menu_window", "Welkom  "))
        self.quit.setText(_translate("menu_window", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    menu_window = QtWidgets.QMainWindow()
    ui = Ui_menu_window()
    ui.setupUi(menu_window)
    menu_window.show()
    sys.exit(app.exec_())